# Generated by Django 5.1.15 on 2026-09-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, help_text='Rental rate per calendar day (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Refundable deposit amount (₹)', max_digits=10),
        ),
    ]
