# Generated by Django 5.1.15 on 2026-09-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RENTER', 'Renter / Farmer'), ('OWNER', 'Equipment Owner')], default='RENTER', help_text='Designates whether the user is primarily a renter or equipment owner.', max_length=20, verbose_name='User Role'),
        ),
    ]
