# Generated by Django 5.1.15 on 2026-09-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Detailed feedback and review comment (optional)'),
        ),
    ]
